# Generated by Django 3.2.6 on 2022-09-04 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=80, verbose_name='Apellido')),
                ('nationality', models.CharField(max_length=80, verbose_name='Nacionalidad')),
                ('age', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Lector',
                'verbose_name_plural': 'Lectores',
                'db_table': 'reader',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_loan', models.DateField(verbose_name='Fecha Préstamo')),
                ('date_return', models.DateField(blank=True, null=True, verbose_name='Fecha Devolución')),
                ('is_returned', models.BooleanField(default=False, verbose_name='Devuelto')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_loan', to='books.book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.reader')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'db_table': 'loan',
                'ordering': ['-id'],
            },
        ),
    ]
