# Generated by Django 3.2.6 on 2022-09-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
